 CREATE TABLE "MESSAGE_DETAIL" 
   (	"ID" NUMBER, 
	"TEXT" VARCHAR2(160), 
	"ORIGINATOR" VARCHAR2(11), 
	"COMPLETED" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"STARTDATE" TIMESTAMP (6), 
	"USERID" NUMBER, 
	 CONSTRAINT "MESSAGE_DETAIL_PK" PRIMARY KEY ("ID"));


 CREATE TABLE "MESSAGES" 
   (	"ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"DETAILID" NUMBER NOT NULL ENABLE, 
	"DESTINATION" VARCHAR2(100) NOT NULL ENABLE, 
	"SENDINGSTATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"TRANSACTIONID" VARCHAR2(100), 
	"RETRYCOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"STATE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PROCESSINGDATE" TIMESTAMP (6), 
	"DELIVERYDATE" TIMESTAMP (6), 
	 CONSTRAINT "OUTGOING_SMS_PK" PRIMARY KEY ("ID"));
	 
	 
	  CREATE SEQUENCE "MESSAGE_ID_SEQ"  MINVALUE 0 MAXVALUE
	  9999999999999999999999999999 INCREMENT BY 1 START WITH 42 NOCACHE  
	  NOORDER  NOCYCLE ; 
 
	  
	  CREATE TABLE "MESSAGE_HISTORY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DETAILID" VARCHAR2(500) NOT NULL ENABLE, 
	"DESTINATION" VARCHAR2(100) NOT NULL ENABLE, 
	"DELIVERYDATE" TIMESTAMP (6), 
	"TRANSACTIONID" VARCHAR2(100), 
	"MESSAGESTATE" NUMBER, 
	 CONSTRAINT "MESSAGE_HISTORY_PK" PRIMARY KEY ("ID"));